name: Deploy Industry 4.0 App to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          lfs: true 
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://Nitin190606:$HF_TOKEN@huggingface.co/spaces/Nitin190606/Industry-Predictive-AI main